version: 0.2

phases:
  pre_build:
    commands:
      - PACKAGE_VERSION=$(node -e "console.log(require('./package.json').version)")
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 868315650324.dkr.ecr.us-east-2.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t 868315650324.dkr.ecr.us-east-2.amazonaws.com/tst/nodejs-system:latest .
      - docker tag 868315650324.dkr.ecr.us-east-2.amazonaws.com/tst/nodejs-system:latest 868315650324.dkr.ecr.us-east-2.amazonaws.com/tst/nodejs-system:${PACKAGE_VERSION}
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 868315650324.dkr.ecr.us-east-2.amazonaws.com/tst/nodejs-system:latest
      - docker push 868315650324.dkr.ecr.us-east-2.amazonaws.com/tst/nodejs-system:${PACKAGE_VERSION}
