version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 868315650324.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t node-teste .
      - docker tag node-teste:latest 868315650324.dkr.ecr.us-east-1.amazonaws.com/node-teste:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 868315650324.dkr.ecr.us-east-1.amazonaws.com/node-teste:latest
artifacts:
  files:
  - appspec.yaml